mysite/blog/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'blog'
urlpatterns = [

    path('', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',views.post_detail,name='post_detail'),
    path('create', views.post_create, name='post_create'),
    path('<int:id>/update', views.post_update, name='post_update'),
    path('<int:id>/delete', views.post_delete, name='post_delete'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mysite/blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User
# Create your models here.


class Post(models.Model):
    STATUS_CHOICES = (
    ('draft', 'Draft'),
    ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,unique_for_date='publish')
    author = models.ForeignKey(User,on_delete=models.CASCADE,related_name='blog_posts')
    body = models.TextField()
    image=models.ImageField(blank=True,null=True,
                            width_field="width_field",
                            height_field="height_field")
    width_field=models.IntegerField(default=0)
    height_field=models.IntegerField(default=0)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,choices=STATUS_CHOICES,default='published')

    class Meta:
     ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])

mysite/blog/forms.py
from django import forms
from .models import Post

class post_form(forms.ModelForm):
    class Meta:
        model=Post
        fields=[
            'title',
            'slug',
            'author',
            'body',
            'image',


        ]

mysite/blog/views.py
from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# Create your views here.
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post
from django.db.models import Q
from .forms import post_form
from django.http import HttpResponseRedirect


def post_list(request):
    posts = Post.objects.all()
    q = request.GET.get('q')
    if q:
        posts = posts.filter(
            Q(title__icontains=q) |
            Q(body__icontains=q) |
            Q(slug__icontains=q)
        )
    paginator = Paginator(posts, 3)  # 3 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'page': page, 'posts': posts})


# ========================================================================

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)
    return render(request, 'blog/post/detail.html', {'post': post})


# ==========================================================================
def post_create(request):
    form = post_form(request.POST or None,request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {
        'form': form,
        'btn': 'Create'
    }
    return render(request, 'form.html', context)


# ===========================================================================
def post_update(request, id):
    post = get_object_or_404(Post, id=id)
    form = post_form(request.POST or None,request.FILES or None,instance=post)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        return HttpResponseRedirect(post.get_absolute_url())
    context = {
        'form': form,
        'post': post,
        'btn': 'Update',
    }
    return render(request, 'form.html', context)


# ============================================================================
def post_delete(request, id):
    post = get_object_or_404(Post, id=id)
    post.delete()
    return redirect('/blog')

mysite/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title>{% block title %}{% endblock %}</title>
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">


</head>
<body>
<div class="container">
<div id="content">

{% block content %}
{% endblock %}
</div>
<div id="sidebar">

</div>

</div>


<script src="{% static 'js/bootstrap.js' %}"></script>
</body>
</html>

mysite/blog/templates/blog/pagination.html
<div class="pagination">
<span class="step-links" style="margin:auto;">
{% if page.has_previous %}
<a href="?page={{ page.previous_page_number }}">Previous</a>
{% endif %}
<span class="current">
Page {{ page.number }} of {{ page.paginator.num_pages }}.
</span>
{% if page.has_next %}
<a href="?page={{ page.next_page_number }}">Next</a>
{% endif %}
</span>
</div>

mysite/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% block title %}
    {{ post.title }}
{% endblock %}
{% block content %}
     <div class="col-sm-6 offset-sm-3 col-xs-offset-3">
     {% if post.image %}
    <img src="{{ post.image.url }}" class="img-responsive" width="500px" height="100px">
         {% endif %}
<h1 >

    {{ post.title }}

</h1>
<p class="date">
Published {{ post.publish }}<br><br>by {{ post.author }}
</p>
{{ post.body|linebreaks }}

      <a href ="{% url 'blog:post_list' %}" class="btn btn-info"> Return to List Blog</a>
     <a href="{% url 'blog:post_update' post.id %}" class="btn btn-primary" >Update Post</a>
      <a href="{% url 'blog:post_delete' post.id  %}" class="btn btn-danger" >Delete Post</a>
     </div>

{% endblock %}

mysite/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% block title %}My Blog{% endblock %}
{% block content %}


        <form style="margin-left: 70%;" method="get" action="">
        <input  type="text" name="q" placeholder="search post..." value="{{ request.GET.q }}">
        <input type="submit" value="Search">
        </form>

        <div class="col-sm-6 offset-sm-3 col-xs-offset-3">
        <a href="{% url 'blog:post_create' %}" class="btn btn-success" >Create Post</a>
        <h1 > My Blog </h1>
            {% for post in posts %}
            <div class = "row">
               <div class = "col-md-12 ">
                  <div class = "thumbnail">
            {% if post.image %}
    <img src="{{ post.image.url }}" class="img-responsive" width="500px" height="100px">
         {% endif %}

                  <div class = "caption">
                     <h3><a  href="{{ post.get_absolute_url }}">{{ post.title }}(id:{{ post.id }})</a></h3>
                      <span>Published {{ post.publish }} by {{ post.author }}</span>
                     <p>{{ post.body|truncatewords:70|linebreaks }}</p>
                       <p> <a href = "{{ post.get_absolute_url }}" class = "btn btn-primary" role = "button">Detail
                        </a>
                     </p>
                  </div>
               </div>
            </div>
        </div>
            {% endfor %}
{% include "../pagination.html" with page=posts %}
        </div>



{% endblock %}

mysite/blog/templates/form.html
{% extends "blog/base.html" %}

{% load crispy_forms_tags %}



{% block content %}
        <div class="col-sm-6 offset-sm-3 col-xs-offset-3">

<form style="border: 4px dotted darkcyan;border-radius: 5px" method="post" action="" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input  type="submit"  class="btn btn-primary" value="{{ btn }}" name="">
    </form>
        </div>
{% endblock %}